// sd run: materialise scenarios as Vitest tests, run each with its perturbed twin,
// optionally run the same tests against a base git ref, and classify the results.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { readJson, writeJson, fail, loadRun, rel } from './util.mjs';

function validate(list, label) {
  const errors = [];
  const seen = new Set();
  list.forEach((b, i) => {
    const where = `${label}[${i}]${b && b.id ? ` (${b.id})` : ''}`;
    if (!b || typeof b !== 'object') return errors.push(`${where}: not an object`);
    if (!b.id) errors.push(`${where}: missing id`);
    if (seen.has(b.id)) errors.push(`${where}: duplicate id`);
    seen.add(b.id);
    const t = b.test || {};
    for (const k of ['arrange_act', 'assert', 'twin_assert']) {
      if (typeof t[k] !== 'string') errors.push(`${where}: test.${k} must be a string`);
    }
    if (t.assert && t.twin_assert && t.assert.trim() === t.twin_assert.trim()) {
      errors.push(`${where}: twin_assert is identical to assert`);
    }
  });
  return errors;
}

function testSource(b, upToRoot) {
  const t = b.test;
  const imports = String(t.imports || '').replace(/(['"])@sut\//g, `$1${upToRoot}`);
  const name = (suffix) => JSON.stringify(`${b.id} :: ${suffix}`);
  return `// Generated by silent-decisions. Do not edit.
import { test, expect, vi, beforeEach, afterEach } from 'vitest';
${imports}

test(${name('main')}, async () => {
${t.arrange_act}
${t.assert}
});

test(${name('twin')}, async () => {
${t.arrange_act}
${t.twin_assert}
});
`;
}

function writeTests(list, root, relDir) {
  const dir = path.join(root, relDir);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  const depth = relDir.split('/').filter(Boolean).length;
  const upToRoot = '../'.repeat(depth);
  for (const b of list) fs.writeFileSync(path.join(dir, `${b.id}.test.ts`), testSource(b, upToRoot));
  const cfg = path.join(dir, 'vitest.config.mjs');
  // Own config so the user's `include` cannot hide these files. Pass --vitest-config to use theirs.
  fs.writeFileSync(cfg, `export default { test: { root: ${JSON.stringify(root)}, include: [${JSON.stringify(relDir + '/**/*.test.ts')}], exclude: ['**/node_modules/**'], passWithNoTests: true } };\n`);
  return { dir, cfg };
}

function runVitest(root, cfg, outFile, args) {
  const bin = path.join(root, 'node_modules', '.bin', process.platform === 'win32' ? 'vitest.cmd' : 'vitest');
  if (!fs.existsSync(bin)) fail(`vitest not found in ${root}/node_modules. Install it in the target project: npm i -D vitest`);
  const argv = ['run', '--config', args['vitest-config'] ? path.resolve(root, String(args['vitest-config'])) : cfg,
    '--reporter=json', `--outputFile=${outFile}`];
  if (args['vitest-config']) argv.push(path.dirname(cfg));
  const res = spawnSync(bin, argv, { cwd: root, encoding: 'utf8', env: { ...process.env, CI: '1' } });
  if (!fs.existsSync(outFile)) {
    fail(`vitest produced no report.\n${res.stdout || ''}\n${res.stderr || ''}`);
  }
  const report = readJson(outFile);
  const byTitle = new Map();
  for (const file of report.testResults || []) {
    const id = path.basename(file.name).replace(/\.test\.ts$/, '');
    if ((file.assertionResults || []).length === 0) {
      // Collection error (bad import, syntax error): both tests count as failed.
      byTitle.set(`${id} :: main`, { status: 'failed', message: file.message || 'test file failed to load' });
      byTitle.set(`${id} :: twin`, { status: 'failed', message: file.message || 'test file failed to load' });
    }
    for (const a of file.assertionResults || []) {
      byTitle.set(a.title, { status: a.status, message: (a.failureMessages || []).join('\n').slice(0, 600) });
    }
  }
  return byTitle;
}

function classify(list, head, base) {
  return list.map((b) => {
    const m = head.get(`${b.id} :: main`) || { status: 'missing' };
    const t = head.get(`${b.id} :: twin`) || { status: 'missing' };
    let status;
    if (m.status !== 'passed') status = 'refuted';       // the code does not do this
    else if (t.status === 'passed') status = 'vacuous';  // the test cannot tell outcomes apart
    else status = 'verified';
    const out = { id: b.id, status, main: m.status, twin: t.status };
    if (status === 'refuted') out.message = m.message;
    if (base && status === 'verified') {
      const bm = base.get(`${b.id} :: main`) || { status: 'missing' };
      out.on_base = bm.status === 'passed' ? 'preexisting' : 'introduced';
    }
    return out;
  });
}

function runOnBase(list, meta, relDir, args) {
  const proj = meta.project;
  const wt = fs.mkdtempSync(path.join(os.tmpdir(), 'sd-base-'));
  const git = (...a) => spawnSync('git', a, { cwd: proj, encoding: 'utf8' });
  const add = git('worktree', 'add', '--detach', wt, meta.base);
  if (add.status !== 0) fail(`git worktree add failed for base ref "${meta.base}":\n${add.stderr}`);
  try {
    const nm = path.join(proj, 'node_modules');
    if (fs.existsSync(nm) && !fs.existsSync(path.join(wt, 'node_modules'))) fs.symlinkSync(nm, path.join(wt, 'node_modules'), 'dir');
    const { cfg } = writeTests(list, wt, relDir);
    return runVitest(wt, cfg, path.join(wt, relDir, 'report.json'), args);
  } finally {
    git('worktree', 'remove', '--force', wt);
    fs.rmSync(wt, { recursive: true, force: true });
  }
}

/** sd run [--probes]: behaviours by default, reverse probes with --probes. */
export function run(args) {
  const { proj, runDir, meta } = loadRun(args);
  const probes = Boolean(args.probes);
  let list;
  if (probes) {
    const p = path.join(runDir, 'probes.json');
    if (!fs.existsSync(p)) fail(`missing ${rel(proj, p)}`);
    list = (readJson(p).probes || []).map((x) => ({ ...x, id: x.id || `PR-${x.statement_id}` }));
  } else {
    // The extractor writes into the room; collect its output into the run directory.
    const src = path.join(meta.room_root, 'out', 'behaviours.json');
    const dst = path.join(runDir, 'behaviours.json');
    if (fs.existsSync(src)) fs.copyFileSync(src, dst);
    if (!fs.existsSync(dst)) fail(`no behaviours.json in ${meta.room_root}/out or the run directory`);
    list = readJson(dst).behaviours || [];
  }
  const errors = validate(list, probes ? 'probes' : 'behaviours');
  if (errors.length) fail('invalid input:\n  ' + errors.join('\n  '));

  const relDir = rel(proj, path.join(runDir, probes ? 'probe-tests' : 'tests'));
  const { cfg } = writeTests(list, proj, relDir);
  const head = runVitest(proj, cfg, path.join(proj, relDir, 'report.json'), args);
  const base = !probes && meta.base ? runOnBase(list, meta, relDir, args) : null;

  let results = classify(list, head, base);
  if (probes) {
    results = results.map((r, i) => ({
      statement_id: list[i].statement_id,
      probe_id: r.id,
      // verified: the code does realise the statement, so the extractor missed it (a recall miss).
      // refuted: confirmed dropped requirement, with this probe as the executable witness.
      outcome: r.status === 'verified' ? 'realised_missed_by_extractor' : r.status === 'refuted' ? 'dropped' : 'inconclusive',
      main: r.main, twin: r.twin, message: r.message,
    }));
  }
  const outPath = path.join(runDir, probes ? 'probes.results.json' : 'results.json');
  writeJson(outPath, { base: base ? meta.base : null, results });
  if (!probes) {
    // What the tracer and adversary see: verified behaviour only (and, with --base, only what
    // the change introduced), without test code or census links.
    const keep = new Set(results.filter((r) => r.status === 'verified' && r.on_base !== 'preexisting').map((r) => r.id));
    const traceable = list.filter((b) => keep.has(b.id)).map(({ test, covers, ...rest }) => rest);
    writeJson(path.join(runDir, 'behaviours.verified.json'), { behaviours: traceable });
  }

  const count = (k, v) => results.filter((r) => r[k] === v).length;
  const summary = probes
    ? { probes: results.length, dropped: count('outcome', 'dropped'), missed_by_extractor: count('outcome', 'realised_missed_by_extractor'), inconclusive: count('outcome', 'inconclusive') }
    : { behaviours: results.length, verified: count('status', 'verified'), vacuous: count('status', 'vacuous'), refuted: count('status', 'refuted'),
        ...(base ? { introduced: count('on_base', 'introduced'), preexisting: count('on_base', 'preexisting') } : {}) };
  process.stdout.write(JSON.stringify({ wrote: rel(proj, outPath), ...summary }, null, 2) + '\n');
}
